### ISSUE TITLE
netcoreapp3.1

### ISSUE THREAD

**Issue by cjonstrup** [star-micronics/cloudprnt-sdk#3]
Should the target not be 3.1 as described in the documentation

Dependent package that is fully platform neutral, but requires a locally installed .NET Core Runtime (3.1 or later) installed.
https://www.star-m.jp/products/s_print/CloudPRNTSDK/Documentation/en/articles/cputil/cputil.html

https://github.com/star-micronics/cloudprnt-sdk/blob/49f1577b2059fcde31050de388c13f08318f117e/CloudPRNTSDKSamples/cputil/cputil.csproj#L5

**Comment by bandit-ibayashi** [comment]
@cjonstrup Thank you for your report. We apologize for any inconvenience caused by the incorrect information.
In version 1.1.2, it has been upgraded to .Net 6, and the documentation has now been corrected.

https://github.com/star-micronics/cloudprnt-sdk/blob/b3e13ac69de63f3b993eb4b9866180eac60f3201/CloudPRNTSDKSamples/cputil/cputil.csproj#L5

https://star-m.jp/products/s_print/sdk/StarCloudPRNT/manual/en/cputil.html
![image](https://github.com/star-micronics/cloudprnt-sdk/assets/60959945/27a24938-c904-414e-8f90-cd5ae03dd2fe)
